In [1]:
x = 2+3

In [2]:
x

5

In [3]:
x = 4

In [4]:
x

4

Ini Bukan Code

$\displaystyle s = \sqrt\frac{\sum(x_{i}-\mu)^2}{n}$



# __1. Intro to Numpy__

In [5]:
import numpy as np

In [6]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [7]:
print(type(my_list))

<class 'list'>


In [8]:
my_array = np.array(my_list)

In [9]:
print (my_list)
print (my_array)

[1, 2, 3]
[1 2 3]


In [10]:
my_array

array([1, 2, 3])

In [11]:
print (type(my_list))
print (type(my_array))

<class 'list'>
<class 'numpy.ndarray'>


In [12]:
my_list2 = ['a','b','c',4,5]
my_array2= np.array (my_list2)

print (my_list2)
print (my_array2)

['a', 'b', 'c', 4, 5]
['a' 'b' 'c' '4' '5']


In [13]:
print (my_list2[3])
print (my_array2[3])

4
4


In [14]:
print (type(my_list2[3]))
print (type(my_array2[3]))

<class 'int'>
<class 'numpy.str_'>


In [15]:
my_list3 = [1.0, 2.5, 4.5, 5,6,7]
my_array3 = np.array(my_list3)
print (my_list3)
print (my_array3)

[1.0, 2.5, 4.5, 5, 6, 7]
[1.  2.5 4.5 5.  6.  7. ]


In [16]:
i = 3
print(type(my_list3))
print(type(my_array3))

<class 'list'>
<class 'numpy.ndarray'>


## __Str<Float<int__

In [17]:
my_list

[1, 2, 3]

In [18]:
my_list4 = [2,3,4]

## __Operasi matematika (+) Menggunakan Array__

In [19]:
my_list + my_list4

[1, 2, 3, 2, 3, 4]

In [20]:
my_array4 = np.array(my_list4)
my_array4

array([2, 3, 4])

In [21]:
my_list + my_array4

array([3, 5, 7])

In [22]:
print(my_array4)
print(my_array4+2)

[2 3 4]
[4 5 6]


## __Operasi Matematika (x) Menggunakan Array__

In [23]:
print(my_array4, my_list)
print(my_array4 * my_list)

[2 3 4] [1, 2, 3]
[ 2  6 12]


In [24]:
print(my_array4, my_array)
print(my_array4 * my_array4)

[2 3 4] [1 2 3]
[ 4  9 16]


## __Array 2 Dimensi__

In [25]:
list_of_list = [[1,2,3],[4,5,6],[7,8,9]]
print(list_of_list)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [26]:
my_matrix = np.array(list_of_list)
print(my_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## __Operasi Array dengan 2 dimensi__

In [27]:
print(my_matrix+3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [28]:
(my_matrix + list_of_list)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [29]:
list_of_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [30]:
list_of_list[2]

[7, 8, 9]

In [31]:
list_of_list[2][2]

9

In [32]:
#indexing : mengambil Value 6
print(my_matrix[1,2])
print(my_matrix[1][2])

6
6


In [33]:
list_of_list2 = [[10,11,12],[13,14,15]]
my_matrix2 = np.array(list_of_list2)
print(my_matrix2)

[[10 11 12]
 [13 14 15]]


In [34]:
my_matrix2.shape #.shape adalah atribut

(2, 3)

In [35]:
print(my_array, my_matrix)

[1 2 3] [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
print(my_array + my_matrix)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [37]:
list_of_list3 =[[[1,2,3],[2,3,4],[3,4,5]],[[4,5,6],[5,6,7],[6,7,8]]]
list_of_list3

[[[1, 2, 3], [2, 3, 4], [3, 4, 5]], [[4, 5, 6], [5, 6, 7], [6, 7, 8]]]

In [38]:
my_matrix3 = np.array(list_of_list3)
print(my_matrix3)

[[[1 2 3]
  [2 3 4]
  [3 4 5]]

 [[4 5 6]
  [5 6 7]
  [6 7 8]]]


In [39]:
my_matrix3[0][1][2]


4

In [40]:
my_matrix3.shape

(2, 3, 3)

In [41]:
print(my_array)
my_array.shape

[1 2 3]


(3,)

# __2.Build-in Method__

## __2.1 arange()__

In [42]:
#python
ar1 = range(0,10)
set(ar1)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [43]:
#numpy
nar1 = np.arange (0,10)
nar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
#python
ar2 = range (0,10,2)
list (ar2)

[0, 2, 4, 6, 8]

In [45]:
#numpy
nar2 = np.arange(0,10,2)
nar2

array([0, 2, 4, 6, 8])

## __2.2 np.zeros()&np.ones()__

In [46]:
zer1 = np.zeros(7)
zer1

array([0., 0., 0., 0., 0., 0., 0.])

In [47]:
zer2 = np.zeros((4,5))
zer2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [48]:
one1 = np.ones(7)
one1


array([1., 1., 1., 1., 1., 1., 1.])

In [49]:
one2 = np.ones((4,2))
one2

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

## __2.3 np.linspace() = membuat data dengan jarak antara data sama__

In [50]:
lin1 = np.linspace(0,1000,101)
lin1

array([   0.,   10.,   20.,   30.,   40.,   50.,   60.,   70.,   80.,
         90.,  100.,  110.,  120.,  130.,  140.,  150.,  160.,  170.,
        180.,  190.,  200.,  210.,  220.,  230.,  240.,  250.,  260.,
        270.,  280.,  290.,  300.,  310.,  320.,  330.,  340.,  350.,
        360.,  370.,  380.,  390.,  400.,  410.,  420.,  430.,  440.,
        450.,  460.,  470.,  480.,  490.,  500.,  510.,  520.,  530.,
        540.,  550.,  560.,  570.,  580.,  590.,  600.,  610.,  620.,
        630.,  640.,  650.,  660.,  670.,  680.,  690.,  700.,  710.,
        720.,  730.,  740.,  750.,  760.,  770.,  780.,  790.,  800.,
        810.,  820.,  830.,  840.,  850.,  860.,  870.,  880.,  890.,
        900.,  910.,  920.,  930.,  940.,  950.,  960.,  970.,  980.,
        990., 1000.])

In [51]:
lin1.shape

(101,)

## __2.4 np.eye() & np.identity() = membuat data/,atrix dengan angka 1 pada area diagonal dari kiri ke kanan dan angka 0 di area yang lain__

In [52]:
eye1 = np.eye(5,5)
eye1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
eye2 = np.eye(5,2)
eye2

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [54]:
eye3 = np.eye(3, k=1)
eye3

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [55]:
iden1 = np.identity (4)
iden1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## __2.5 np.random.rand() = membuat array dengan random value 0-1__

In [56]:
np.random.seed(25) #mengontrol randomiceingnya
rand1 = np.random.rand(10)
rand1

array([0.87012414, 0.58227693, 0.27883894, 0.18591123, 0.41110013,
       0.11737555, 0.68496874, 0.43761106, 0.55622933, 0.36708032])

In [57]:
np.random.seed(25) #mengontrol randomiceingnya
rand2 = np.random.rand(5,5)
rand2

array([[0.87012414, 0.58227693, 0.27883894, 0.18591123, 0.41110013],
       [0.11737555, 0.68496874, 0.43761106, 0.55622933, 0.36708032],
       [0.40236573, 0.1130407 , 0.44703085, 0.58544512, 0.1619851 ],
       [0.52071879, 0.32605113, 0.69918624, 0.36639455, 0.83637451],
       [0.48134294, 0.5165023 , 0.38304813, 0.9975409 , 0.51424449]])

## __2.6 np.random.randint() = membuat data atau array dengan value random dan datanya berupa integer__

In [58]:
randint1 = np.random.randint(1,15) # 1 dimensi
randint1 

3

In [59]:
randint2 = np.random.randint(1,15,10) #menampilkan 10 data
randint2

array([13,  5,  3,  6,  9, 12,  1,  7,  5,  3])

In [60]:
randint3 = np.random.randint(1,15,(5,5))
randint3

array([[ 6, 10, 10,  7,  1],
       [12,  3, 12, 11, 14],
       [ 5,  4, 11,  2,  4],
       [ 6, 11,  8,  3,  4],
       [ 8, 11, 13,  8,  9]])

## __2.7 np.reshape() = mengubah bentuk dari arraynya__

In [61]:
my_array5 = np.random.randint (1,10,20)
my_array5

array([4, 6, 6, 6, 4, 3, 9, 4, 1, 6, 9, 5, 4, 4, 6, 3, 8, 2, 7, 8])

In [62]:
my_array5.shape

(20,)

In [63]:
my_matrix6 = my_array5.reshape(2,5,2)
my_matrix6

array([[[4, 6],
        [6, 6],
        [4, 3],
        [9, 4],
        [1, 6]],

       [[9, 5],
        [4, 4],
        [6, 3],
        [8, 2],
        [7, 8]]])

In [64]:
my_array6 = np.random.randint(1,10,125)
my_array6

array([9, 8, 4, 3, 4, 2, 8, 4, 9, 1, 1, 4, 8, 1, 1, 5, 5, 9, 7, 8, 1, 8,
       3, 7, 1, 1, 5, 6, 4, 1, 1, 5, 2, 3, 7, 2, 6, 1, 4, 7, 2, 2, 3, 9,
       7, 4, 5, 8, 1, 3, 8, 6, 8, 1, 8, 3, 1, 6, 7, 9, 7, 3, 3, 6, 6, 6,
       5, 5, 8, 7, 1, 4, 9, 9, 1, 7, 7, 7, 1, 5, 8, 7, 7, 2, 4, 5, 8, 6,
       5, 2, 1, 4, 3, 8, 3, 6, 3, 9, 4, 5, 9, 7, 1, 9, 1, 3, 1, 6, 2, 8,
       7, 3, 8, 2, 2, 4, 8, 2, 3, 4, 4, 7, 6, 9, 1])

In [65]:
my_matrix7 = my_array6.reshape(-1,5)
my_matrix7

array([[9, 8, 4, 3, 4],
       [2, 8, 4, 9, 1],
       [1, 4, 8, 1, 1],
       [5, 5, 9, 7, 8],
       [1, 8, 3, 7, 1],
       [1, 5, 6, 4, 1],
       [1, 5, 2, 3, 7],
       [2, 6, 1, 4, 7],
       [2, 2, 3, 9, 7],
       [4, 5, 8, 1, 3],
       [8, 6, 8, 1, 8],
       [3, 1, 6, 7, 9],
       [7, 3, 3, 6, 6],
       [6, 5, 5, 8, 7],
       [1, 4, 9, 9, 1],
       [7, 7, 7, 1, 5],
       [8, 7, 7, 2, 4],
       [5, 8, 6, 5, 2],
       [1, 4, 3, 8, 3],
       [6, 3, 9, 4, 5],
       [9, 7, 1, 9, 1],
       [3, 1, 6, 2, 8],
       [7, 3, 8, 2, 2],
       [4, 8, 2, 3, 4],
       [4, 7, 6, 9, 1]])

## __2.8 arr.mx__


In [66]:
my_matrix6.max()

9

In [67]:
my_matrix6.argmax()

6

In [68]:
flat = my_matrix7.flatten()
ravel = my_matrix7.ravel() 

In [69]:
flat[0] = 1
print(flat)
print(my_matrix7)

[1 8 4 3 4 2 8 4 9 1 1 4 8 1 1 5 5 9 7 8 1 8 3 7 1 1 5 6 4 1 1 5 2 3 7 2 6
 1 4 7 2 2 3 9 7 4 5 8 1 3 8 6 8 1 8 3 1 6 7 9 7 3 3 6 6 6 5 5 8 7 1 4 9 9
 1 7 7 7 1 5 8 7 7 2 4 5 8 6 5 2 1 4 3 8 3 6 3 9 4 5 9 7 1 9 1 3 1 6 2 8 7
 3 8 2 2 4 8 2 3 4 4 7 6 9 1]
[[9 8 4 3 4]
 [2 8 4 9 1]
 [1 4 8 1 1]
 [5 5 9 7 8]
 [1 8 3 7 1]
 [1 5 6 4 1]
 [1 5 2 3 7]
 [2 6 1 4 7]
 [2 2 3 9 7]
 [4 5 8 1 3]
 [8 6 8 1 8]
 [3 1 6 7 9]
 [7 3 3 6 6]
 [6 5 5 8 7]
 [1 4 9 9 1]
 [7 7 7 1 5]
 [8 7 7 2 4]
 [5 8 6 5 2]
 [1 4 3 8 3]
 [6 3 9 4 5]
 [9 7 1 9 1]
 [3 1 6 2 8]
 [7 3 8 2 2]
 [4 8 2 3 4]
 [4 7 6 9 1]]


In [70]:
ravel[0] = 1
print(ravel)
print(my_matrix7)

[1 8 4 3 4 2 8 4 9 1 1 4 8 1 1 5 5 9 7 8 1 8 3 7 1 1 5 6 4 1 1 5 2 3 7 2 6
 1 4 7 2 2 3 9 7 4 5 8 1 3 8 6 8 1 8 3 1 6 7 9 7 3 3 6 6 6 5 5 8 7 1 4 9 9
 1 7 7 7 1 5 8 7 7 2 4 5 8 6 5 2 1 4 3 8 3 6 3 9 4 5 9 7 1 9 1 3 1 6 2 8 7
 3 8 2 2 4 8 2 3 4 4 7 6 9 1]
[[1 8 4 3 4]
 [2 8 4 9 1]
 [1 4 8 1 1]
 [5 5 9 7 8]
 [1 8 3 7 1]
 [1 5 6 4 1]
 [1 5 2 3 7]
 [2 6 1 4 7]
 [2 2 3 9 7]
 [4 5 8 1 3]
 [8 6 8 1 8]
 [3 1 6 7 9]
 [7 3 3 6 6]
 [6 5 5 8 7]
 [1 4 9 9 1]
 [7 7 7 1 5]
 [8 7 7 2 4]
 [5 8 6 5 2]
 [1 4 3 8 3]
 [6 3 9 4 5]
 [9 7 1 9 1]
 [3 1 6 2 8]
 [7 3 8 2 2]
 [4 8 2 3 4]
 [4 7 6 9 1]]
