In [1]:
x = 2+3

In [2]:
x

5

In [3]:
x = 4

ini bukan code

$\displaystyle s = \sqrt\frac{\sum(x_{i}-\mu)^2}{n}$

## __1. Intro Numpy__

In [4]:
import numpy as np

In [5]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [6]:
print(type(my_list))

<class 'list'>


In [7]:
my_array = np.array(my_list)

In [8]:
print(my_list)
print(my_array)

[1, 2, 3]
[1 2 3]


In [9]:
my_array

array([1, 2, 3])

In [10]:
print(type(my_list))
print(type(my_array))

<class 'list'>
<class 'numpy.ndarray'>


In [11]:
my_list2 = ['a', 'b', 'c', 4, 5]
my_array2 = np.array(my_list2)

print(my_list2)
print(my_array2)

['a', 'b', 'c', 4, 5]
['a' 'b' 'c' '4' '5']


In [12]:
i = 3
print(type(my_list2[i]))
print(type(my_array2[i]))

<class 'int'>
<class 'numpy.str_'>


In [13]:
my_list3 = [1.0, 2.5, 4.5, 5, 6, 7, 'a']
my_array3 = np.array(my_list3)

print(my_list3)
print(my_array3)

[1.0, 2.5, 4.5, 5, 6, 7, 'a']
['1.0' '2.5' '4.5' '5' '6' '7' 'a']


In [14]:
i = 3
print(type(my_list3[i]))
print(type(my_array3[i]))

<class 'int'>
<class 'numpy.str_'>


### __str < float < int__

In [15]:
my_list

[1, 2, 3]

In [16]:
my_list4 = [2,3,4]

## __Operasi Matematika (+) Menggunakan Array__

In [17]:
my_list + my_list4

[1, 2, 3, 2, 3, 4]

In [18]:
my_array4 = np.array(my_list4)
my_array4

array([2, 3, 4])

In [19]:
my_list + my_array4

array([3, 5, 7])

In [20]:
print(my_array4)
print(my_array4 + 1)

[2 3 4]
[3 4 5]


## __Operasi Matematika (x) Menggunakan Array__

In [21]:
print(my_array4, my_list)
print(my_array4 * my_list)

[2 3 4] [1, 2, 3]
[ 2  6 12]


In [22]:
print(my_array4, my_array)
print(my_array4 * my_array)

[2 3 4] [1 2 3]
[ 2  6 12]


## __Array 2 Dimensi__

In [23]:
list_of_list = [[1,2,3], [4,5,6], [7,8,9]]
print(list_of_list)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [24]:
my_matrix = np.array(list_of_list)
print(my_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## __Operasi Matematika Dengan Array 2 Dimensi__

In [26]:
print(my_matrix)
print(my_matrix + 3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [27]:
print(my_matrix + list_of_list)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [28]:
list_of_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [29]:
list_of_list[2][2]

9

In [30]:
print(my_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
# indexing : mengambil value 6
print(my_matrix[1,2])
print(my_matrix[1][2])

6
6


In [32]:
list_of_list2 = [[10,11,12], [13,14,15]]
my_matrix2 = np.array(list_of_list2)
print(my_matrix2)

[[10 11 12]
 [13 14 15]]


In [33]:
# my_matrix + my_matrix2

In [34]:
my_matrix2.shape

(2, 3)

In [35]:
my_array, my_matrix

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [36]:
my_array + my_matrix

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [37]:
my_array

array([1, 2, 3])

In [38]:
my_array

array([1, 2, 3])

In [39]:
list_of_list3 = [[[1,2,3],[2,3,4],[3,4,5]], [[4,5,6], [5,6,7], [6,7,8]]]
list_of_list3

[[[1, 2, 3], [2, 3, 4], [3, 4, 5]], [[4, 5, 6], [5, 6, 7], [6, 7, 8]]]

In [40]:
my_matrix3 = np.array(list_of_list3)
print(my_matrix3)

[[[1 2 3]
  [2 3 4]
  [3 4 5]]

 [[4 5 6]
  [5 6 7]
  [6 7 8]]]


In [41]:
# my_matrix3[0][1][2]
my_matrix3[0,1,2]

4

In [42]:
my_matrix3.shape

(2, 3, 3)

In [43]:
my_array.shape

(3,)

In [44]:
my_matrix4 = np.array([[1,2,3]])
my_matrix4

array([[1, 2, 3]])

In [45]:
my_matrix4.shape

(1, 3)

## __2. Built-in Method__

### __2.1 np.arange()__

In [46]:
#python
ar1 = range(0,10)
set(ar1)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [47]:
#numpy
nar1 = np.arange(0,10)
nar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
print(type(nar1))

<class 'numpy.ndarray'>


In [49]:
#python
ar2 = range(0,10,2)
list(ar2)

[0, 2, 4, 6, 8]

In [50]:
#numpy     (start, stop, step)
nar2 = np.arange(0,10,2)
nar2

array([0, 2, 4, 6, 8])

### __2.2 np.zeros() & np.ones()__

In [51]:
zer1 = np.zeros(7)
zer1

array([0., 0., 0., 0., 0., 0., 0.])

In [52]:
zer2 = np.zeros((4,5))
zer2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [53]:
zer2.shape

(4, 5)

In [54]:
len(zer2)

4

In [55]:
one1 = np.ones(7)
one1

array([1., 1., 1., 1., 1., 1., 1.])

In [56]:
one2 = np.ones((4,2))
one2

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

### __2.3 np.linspace(): membuat data dengan jarak antar data yang sama besarnya__

In [57]:
lin1 = np.linspace(0,1000,101)
lin1.shape

(101,)

In [58]:
len(lin1)

101

### __2.4 np.eye() & np.identity(): membuat data/matrix dengan angka 1 pada area diagonal dan angka 0 di area yang lain__

In [59]:
eye1 = np.eye(5,k=0)
eye1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [60]:
eye2 = np.eye(2)
eye2

array([[1., 0.],
       [0., 1.]])

In [61]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### __2.5 np.random.rand(): membuat array dengan random value antara 0-1__

In [157]:
np.random.seed(1000) # pseudorandom generator
# random_state = 25

rand1 = np.random.rand(10)
rand1

array([0.76170284, 0.51759996, 0.14199825, 0.68498959, 0.41403634,
       0.87616029, 0.11662097, 0.27764468, 0.41781302, 0.78018246])

In [165]:
type(np.array([9223372036854775808])[0])

numpy.uint64

In [71]:
np.random.seed(25)

rand2 = np.random.rand(5,5)
rand2

array([[0.87012414, 0.58227693, 0.27883894, 0.18591123, 0.41110013],
       [0.11737555, 0.68496874, 0.43761106, 0.55622933, 0.36708032],
       [0.40236573, 0.1130407 , 0.44703085, 0.58544512, 0.1619851 ],
       [0.52071879, 0.32605113, 0.69918624, 0.36639455, 0.83637451],
       [0.48134294, 0.5165023 , 0.38304813, 0.9975409 , 0.51424449]])

In [74]:
# intermezo
normal1 = np.random.normal(0, 1, 100)
normal1

array([-0.54703373, -0.68721296,  0.59582659, -0.58454248, -0.40414387,
       -0.02999772, -0.63509455, -0.38540704, -1.48968252,  1.81242188,
       -0.70870232, -0.48619647,  1.02729571, -0.21726222,  1.53501334,
       -0.29662297,  1.41018007,  0.57334548,  1.76307093, -0.38452998,
       -0.69125558,  0.56009601,  0.04445408, -1.94396222, -0.03787484,
       -0.38929618,  1.98125369, -0.65002839,  0.39750003, -0.43899976,
       -1.90931669, -0.23835026,  0.56987255, -1.80072841,  0.05813591,
        0.61410926,  0.89342064,  0.87079764, -0.05940406,  0.21629372,
        0.13396835,  0.67653236, -0.4392725 , -0.29030249,  0.74036241,
       -0.76738582,  1.48635353,  0.31082932, -0.54441745,  0.14973437,
        0.36172323,  0.58275743, -1.46873459,  0.22287969,  0.33679243,
        1.93760118, -0.09518122, -1.11161866,  1.71323995, -1.02311245,
        1.36548169, -0.20893539, -0.44661471,  1.08940116,  0.18895259,
        0.68972803, -1.66087214, -0.78327262,  2.18698102, -1.84

### __2.6 np.random.randint(): membuat data atau array dengan value random dan datanya berupa integer__

In [77]:
randint1 = np.random.randint(1,15)
randint1

2

In [78]:
randint2 = np.random.randint(1,15,10)
randint2

array([ 6,  2,  3, 11,  3, 13,  4,  1,  5,  2])

In [79]:
randint3 = np.random.randint(1,15,(5,5))
randint3

array([[14,  5,  4,  1,  4],
       [13,  4,  9, 12, 13],
       [ 3,  3, 11,  7, 13],
       [ 1, 14,  2, 12,  5],
       [14, 13,  4, 12,  9]])

### __2.7 np.reshape()__

In [82]:
my_array5 = np.random.randint(1,10,20)
my_array5

array([2, 9, 5, 6, 1, 5, 2, 6, 6, 4, 3, 2, 7, 1, 9, 4, 6, 4, 5, 2])

In [84]:
my_array5.shape

(20,)

In [90]:
# faktor dari 20 = 1,2,4,5,10,20
my_matrix5 = my_array5.reshape(5,4) # 20
my_matrix5

array([[2, 9, 5, 6],
       [1, 5, 2, 6],
       [6, 4, 3, 2],
       [7, 1, 9, 4],
       [6, 4, 5, 2]])

In [104]:
# my_matrix6 = my_array5.reshape(2,5,2) sama dengan yang bawah
my_matrix6 = my_array5.reshape(2,5,-1)
my_matrix6

array([[[2, 9],
        [5, 6],
        [1, 5],
        [2, 6],
        [6, 4]],

       [[3, 2],
        [7, 1],
        [9, 4],
        [6, 4],
        [5, 2]]])

In [105]:
my_matrix6.shape

(2, 5, 2)

In [118]:
my_array6 = np.random.randint(1,10,125)
my_array6

array([3, 1, 6, 9, 8, 9, 1, 9, 6, 8, 7, 8, 5, 7, 6, 2, 4, 8, 4, 7, 6, 2,
       5, 4, 6, 7, 9, 8, 3, 4, 1, 8, 2, 2, 1, 5, 4, 1, 4, 6, 3, 8, 2, 6,
       8, 1, 7, 6, 2, 9, 1, 2, 2, 4, 1, 3, 2, 7, 4, 7, 8, 8, 4, 5, 6, 5,
       9, 2, 1, 2, 5, 9, 9, 2, 3, 4, 9, 9, 6, 1, 4, 3, 1, 8, 1, 2, 9, 9,
       1, 3, 7, 7, 4, 8, 7, 5, 7, 7, 8, 2, 8, 9, 3, 6, 5, 4, 8, 3, 1, 6,
       8, 2, 1, 9, 2, 8, 6, 5, 3, 7, 2, 2, 5, 8, 4])

In [119]:
# -1 berarti menyerahkan kembali ke numpy berapa pasangan faktornya
my_matrix7 = my_array6.reshape(-1,5)
my_matrix7

array([[3, 1, 6, 9, 8],
       [9, 1, 9, 6, 8],
       [7, 8, 5, 7, 6],
       [2, 4, 8, 4, 7],
       [6, 2, 5, 4, 6],
       [7, 9, 8, 3, 4],
       [1, 8, 2, 2, 1],
       [5, 4, 1, 4, 6],
       [3, 8, 2, 6, 8],
       [1, 7, 6, 2, 9],
       [1, 2, 2, 4, 1],
       [3, 2, 7, 4, 7],
       [8, 8, 4, 5, 6],
       [5, 9, 2, 1, 2],
       [5, 9, 9, 2, 3],
       [4, 9, 9, 6, 1],
       [4, 3, 1, 8, 1],
       [2, 9, 9, 1, 3],
       [7, 7, 4, 8, 7],
       [5, 7, 7, 8, 2],
       [8, 9, 3, 6, 5],
       [4, 8, 3, 1, 6],
       [8, 2, 1, 9, 2],
       [8, 6, 5, 3, 7],
       [2, 2, 5, 8, 4]])

In [102]:
my_matrix7.shape

(25, 5)

In [1]:
# my_array6.reshape(-1,-1) #error

In [117]:
my_array6[::-1]

array([5, 9, 3, 9, 5, 2, 9, 3, 2, 3, 6, 6, 2, 1, 7, 2, 8, 3, 2, 4, 1, 1,
       6, 8, 2, 3, 9, 9, 2, 1, 8, 5, 8, 3, 4, 8, 1, 8, 8, 6, 9, 5, 4, 4,
       3, 8, 2, 7, 6, 5, 1, 1, 7, 6, 6, 8, 4, 1, 7, 4, 8, 5, 1, 9, 2, 4,
       6, 3, 7, 5, 6, 6, 3, 8, 8, 9, 7, 2, 2, 5, 8, 2, 1, 5, 3, 9, 4, 5,
       9, 6, 6, 9, 9, 1, 7, 4, 5, 1, 8, 6, 4, 1, 1, 7, 5, 2, 2, 5, 7, 1,
       1, 7, 8, 9, 9, 7, 7, 8, 5, 1, 1, 3, 6, 3, 1])

### __2.8 arr.max() & arr.argmax()__ 

In [106]:
my_matrix7.max()

9

In [107]:
my_matrix7.argmax()

10

In [120]:
flat = my_matrix7.flatten() # copy
ravel = my_matrix7.ravel() # view

In [125]:
a = [1,2,3,4]
b = a # => ravel
c = a.copy() # => flatten

b[0]=2
a, b

c[1] = 8
a, c

([2, 2, 3, 4], [1, 8, 3, 4])

In [121]:
flat

array([3, 1, 6, 9, 8, 9, 1, 9, 6, 8, 7, 8, 5, 7, 6, 2, 4, 8, 4, 7, 6, 2,
       5, 4, 6, 7, 9, 8, 3, 4, 1, 8, 2, 2, 1, 5, 4, 1, 4, 6, 3, 8, 2, 6,
       8, 1, 7, 6, 2, 9, 1, 2, 2, 4, 1, 3, 2, 7, 4, 7, 8, 8, 4, 5, 6, 5,
       9, 2, 1, 2, 5, 9, 9, 2, 3, 4, 9, 9, 6, 1, 4, 3, 1, 8, 1, 2, 9, 9,
       1, 3, 7, 7, 4, 8, 7, 5, 7, 7, 8, 2, 8, 9, 3, 6, 5, 4, 8, 3, 1, 6,
       8, 2, 1, 9, 2, 8, 6, 5, 3, 7, 2, 2, 5, 8, 4])

In [122]:
ravel

array([3, 1, 6, 9, 8, 9, 1, 9, 6, 8, 7, 8, 5, 7, 6, 2, 4, 8, 4, 7, 6, 2,
       5, 4, 6, 7, 9, 8, 3, 4, 1, 8, 2, 2, 1, 5, 4, 1, 4, 6, 3, 8, 2, 6,
       8, 1, 7, 6, 2, 9, 1, 2, 2, 4, 1, 3, 2, 7, 4, 7, 8, 8, 4, 5, 6, 5,
       9, 2, 1, 2, 5, 9, 9, 2, 3, 4, 9, 9, 6, 1, 4, 3, 1, 8, 1, 2, 9, 9,
       1, 3, 7, 7, 4, 8, 7, 5, 7, 7, 8, 2, 8, 9, 3, 6, 5, 4, 8, 3, 1, 6,
       8, 2, 1, 9, 2, 8, 6, 5, 3, 7, 2, 2, 5, 8, 4])

In [126]:
flat[0] = 1
print(flat)
print(my_matrix7)

[1 1 6 9 8 9 1 9 6 8 7 8 5 7 6 2 4 8 4 7 6 2 5 4 6 7 9 8 3 4 1 8 2 2 1 5 4
 1 4 6 3 8 2 6 8 1 7 6 2 9 1 2 2 4 1 3 2 7 4 7 8 8 4 5 6 5 9 2 1 2 5 9 9 2
 3 4 9 9 6 1 4 3 1 8 1 2 9 9 1 3 7 7 4 8 7 5 7 7 8 2 8 9 3 6 5 4 8 3 1 6 8
 2 1 9 2 8 6 5 3 7 2 2 5 8 4]
[[3 1 6 9 8]
 [9 1 9 6 8]
 [7 8 5 7 6]
 [2 4 8 4 7]
 [6 2 5 4 6]
 [7 9 8 3 4]
 [1 8 2 2 1]
 [5 4 1 4 6]
 [3 8 2 6 8]
 [1 7 6 2 9]
 [1 2 2 4 1]
 [3 2 7 4 7]
 [8 8 4 5 6]
 [5 9 2 1 2]
 [5 9 9 2 3]
 [4 9 9 6 1]
 [4 3 1 8 1]
 [2 9 9 1 3]
 [7 7 4 8 7]
 [5 7 7 8 2]
 [8 9 3 6 5]
 [4 8 3 1 6]
 [8 2 1 9 2]
 [8 6 5 3 7]
 [2 2 5 8 4]]


In [127]:
ravel[0] = 1
print(ravel)
print(my_matrix7)

[1 1 6 9 8 9 1 9 6 8 7 8 5 7 6 2 4 8 4 7 6 2 5 4 6 7 9 8 3 4 1 8 2 2 1 5 4
 1 4 6 3 8 2 6 8 1 7 6 2 9 1 2 2 4 1 3 2 7 4 7 8 8 4 5 6 5 9 2 1 2 5 9 9 2
 3 4 9 9 6 1 4 3 1 8 1 2 9 9 1 3 7 7 4 8 7 5 7 7 8 2 8 9 3 6 5 4 8 3 1 6 8
 2 1 9 2 8 6 5 3 7 2 2 5 8 4]
[[1 1 6 9 8]
 [9 1 9 6 8]
 [7 8 5 7 6]
 [2 4 8 4 7]
 [6 2 5 4 6]
 [7 9 8 3 4]
 [1 8 2 2 1]
 [5 4 1 4 6]
 [3 8 2 6 8]
 [1 7 6 2 9]
 [1 2 2 4 1]
 [3 2 7 4 7]
 [8 8 4 5 6]
 [5 9 2 1 2]
 [5 9 9 2 3]
 [4 9 9 6 1]
 [4 3 1 8 1]
 [2 9 9 1 3]
 [7 7 4 8 7]
 [5 7 7 8 2]
 [8 9 3 6 5]
 [4 8 3 1 6]
 [8 2 1 9 2]
 [8 6 5 3 7]
 [2 2 5 8 4]]


### __2.9 arr.min() & arr.argmin()__

In [166]:
my_matrix7.min()

1

In [167]:
# index nilai terkecil yang pertama kali ditemui ada di-0
my_matrix7.argmin()

0

### __2.10 arr.dtype()__

In [168]:
my_matrix7.dtype

dtype('int32')

## __3. Indexing & Slicing__

In [169]:
# kita bikin array baru
my_array8 = np.arange(11, 31)
my_array8

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [171]:
len(my_array8)

20

In [172]:
# indexing pada umumnya seperti pada list
my_array8[3]

14

In [173]:
my_array8[0:4]
# index yang di return 0, 1, 2, 3 => sama seperti di list, angka terakhir tidak ikut kena slice.

array([11, 12, 13, 14])

In [175]:
my_array8[0:9:2]
# syntax di atas urutannya start:stop:step. Sama dengan slicing pada list.

array([11, 13, 15, 17, 19])

In [183]:
my_matrix8 = my_matrix7[:10].copy()
my_matrix8

array([[1, 1, 6, 9, 8],
       [9, 1, 9, 6, 8],
       [7, 8, 5, 7, 6],
       [2, 4, 8, 4, 7],
       [6, 2, 5, 4, 6],
       [7, 9, 8, 3, 4],
       [1, 8, 2, 2, 1],
       [5, 4, 1, 4, 6],
       [3, 8, 2, 6, 8],
       [1, 7, 6, 2, 9]])

In [179]:
my_matrix8[4][2]

5

In [180]:
my_matrix8[4,2]

5

## __4. Broadcasting__

In [181]:
my_matrix8

array([[1, 1, 6, 9, 8],
       [9, 1, 9, 6, 8],
       [7, 8, 5, 7, 6],
       [2, 4, 8, 4, 7],
       [6, 2, 5, 4, 6],
       [7, 9, 8, 3, 4],
       [1, 8, 2, 2, 1],
       [5, 4, 1, 4, 6],
       [3, 8, 2, 6, 8],
       [1, 7, 6, 2, 9]])

In [184]:
#my_matrix8[row, kolom]
my_matrix8[0, 0:4] = 0
my_matrix8

array([[0, 0, 0, 0, 8],
       [9, 1, 9, 6, 8],
       [7, 8, 5, 7, 6],
       [2, 4, 8, 4, 7],
       [6, 2, 5, 4, 6],
       [7, 9, 8, 3, 4],
       [1, 8, 2, 2, 1],
       [5, 4, 1, 4, 6],
       [3, 8, 2, 6, 8],
       [1, 7, 6, 2, 9]])

In [185]:
my_matrix8[0:, 0] = 2
my_matrix8

array([[2, 0, 0, 0, 8],
       [2, 1, 9, 6, 8],
       [2, 8, 5, 7, 6],
       [2, 4, 8, 4, 7],
       [2, 2, 5, 4, 6],
       [2, 9, 8, 3, 4],
       [2, 8, 2, 2, 1],
       [2, 4, 1, 4, 6],
       [2, 8, 2, 6, 8],
       [2, 7, 6, 2, 9]])

In [187]:
my_matrix8[0:, 0] = [2,4,1,3,5,6,7,8,9,1]
my_matrix8

array([[2, 0, 0, 0, 8],
       [4, 1, 9, 6, 8],
       [1, 8, 5, 7, 6],
       [3, 4, 8, 4, 7],
       [5, 2, 5, 4, 6],
       [6, 9, 8, 3, 4],
       [7, 8, 2, 2, 1],
       [8, 4, 1, 4, 6],
       [9, 8, 2, 6, 8],
       [1, 7, 6, 2, 9]])

In [188]:
for i in range(5):
    my_matrix8[i, i] = 0
my_matrix8

array([[0, 0, 0, 0, 8],
       [4, 0, 9, 6, 8],
       [1, 8, 0, 7, 6],
       [3, 4, 8, 0, 7],
       [5, 2, 5, 4, 0],
       [6, 9, 8, 3, 4],
       [7, 8, 2, 2, 1],
       [8, 4, 1, 4, 6],
       [9, 8, 2, 6, 8],
       [1, 7, 6, 2, 9]])

### __4.1 np.where()__

In [189]:
np.where(my_matrix8<5)

(array([0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 6, 6, 6, 7, 7, 7,
        8, 9, 9], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 0, 2, 0, 1, 3, 1, 3, 4, 3, 4, 2, 3, 4, 1, 2, 3,
        2, 0, 3], dtype=int64))

In [254]:
my_matrix7[1:3]

array([[9, 1, 9, 6, 8],
       [7, 8, 5, 7, 6]])

In [243]:
my_matrix8

array([[0, 0, 0, 0, 8],
       [4, 0, 9, 6, 8],
       [1, 8, 0, 7, 6],
       [3, 4, 8, 0, 7],
       [5, 2, 5, 4, 0],
       [6, 9, 8, 3, 4],
       [7, 8, 2, 2, 1],
       [8, 4, 1, 4, 6],
       [9, 8, 2, 6, 8],
       [1, 7, 6, 2, 9]])

In [257]:
np.where(my_matrix8<5, 9, my_matrix8)

array([[9, 9, 9, 9, 8],
       [9, 9, 9, 6, 8],
       [9, 8, 9, 7, 6],
       [9, 9, 8, 9, 7],
       [5, 9, 5, 9, 9],
       [6, 9, 8, 9, 9],
       [7, 8, 9, 9, 9],
       [8, 9, 9, 9, 6],
       [9, 8, 9, 6, 8],
       [9, 7, 6, 9, 9]])

In [191]:
np.where(my_array8<20)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64),)

In [199]:
# np.where(kondisinya apa, value ketika kondisi terpenuhi, value ketika kondisi tidak terpenuhi)
my_array9 = np.where(my_array8<20, 0, my_array8)
my_array9

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [195]:
my_array8

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

## __5. arr.copy()__

In [204]:
my_array9 = my_array8.copy()
my_array9

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [205]:
my_array8

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [206]:
my_array9[0] = 100
print(my_array9)
print(my_array8)

[100  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28
  29  30]
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


## __6. Slicing 2D Array__

In [207]:
my_matrix8

array([[0, 0, 0, 0, 8],
       [4, 0, 9, 6, 8],
       [1, 8, 0, 7, 6],
       [3, 4, 8, 0, 7],
       [5, 2, 5, 4, 0],
       [6, 9, 8, 3, 4],
       [7, 8, 2, 2, 1],
       [8, 4, 1, 4, 6],
       [9, 8, 2, 6, 8],
       [1, 7, 6, 2, 9]])

In [208]:
my_matrix8[0:3,2:]

array([[0, 0, 8],
       [9, 6, 8],
       [0, 7, 6]])

In [215]:
my_matrix8[-3::1, 0:2]

array([[8, 4],
       [9, 8],
       [1, 7]])

In [ ]:
'''
[[6],
[7],
[8],
[9],
[1]]

[[8,2,2],
[4,1,4]]

[[6],
[7],
[0],
[4]]
'''

In [218]:
coba_slice = my_matrix8[-5::1,0].reshape(-1,1)
coba_slice

array([[6],
       [7],
       [8],
       [9],
       [1]])

In [221]:
my_matrix8[6:8,1:4]

array([[8, 2, 2],
       [4, 1, 4]])

In [223]:
coba_slice3 = my_matrix8[2:6,-1].reshape(-1,1)
coba_slice3


array([[6],
       [7],
       [0],
       [4]])

## __7. Length Of Array__

In [224]:
my_matrix8

array([[0, 0, 0, 0, 8],
       [4, 0, 9, 6, 8],
       [1, 8, 0, 7, 6],
       [3, 4, 8, 0, 7],
       [5, 2, 5, 4, 0],
       [6, 9, 8, 3, 4],
       [7, 8, 2, 2, 1],
       [8, 4, 1, 4, 6],
       [9, 8, 2, 6, 8],
       [1, 7, 6, 2, 9]])

In [225]:
len(my_matrix8)

10

In [226]:
my_matrix8.shape

(10, 5)

In [227]:
my_matrix7.shape

(25, 5)

## __8. Selection Using Conditional Statement__

In [228]:
gaji = np.random.randint(5,25,20)
gaji

array([16, 14,  5, 22, 14, 22, 17,  8,  9,  9, 12, 15, 19,  6,  7, 11, 23,
       20, 13, 23])

In [229]:
gaji > 10

array([ True,  True, False,  True,  True,  True,  True, False, False,
       False,  True,  True,  True, False, False,  True,  True,  True,
        True,  True])

In [230]:
up_10 = gaji[gaji>10]
up_10

array([16, 14, 22, 14, 22, 17, 12, 15, 19, 11, 23, 20, 13, 23])

In [231]:
len(up_10)/len(gaji)*100

70.0

In [237]:
# ~ = inverse
~(gaji > 10)

array([False, False,  True, False, False, False, False,  True,  True,
        True, False, False, False,  True,  True, False, False, False,
       False, False])

In [235]:
under_10 = gaji[~(gaji>10)]
under_10

array([5, 8, 9, 9, 6, 7])

In [238]:
gaji[np.where(gaji<10)]

array([5, 8, 9, 9, 6, 7])

## __9. Aritmetic__

In [259]:
my_array9

array([100,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30])

In [260]:
my_array10 = np.random.randint(10,15,20)
my_array10

array([11, 13, 12, 12, 10, 11, 13, 10, 10, 13, 12, 11, 10, 11, 10, 12, 12,
       14, 10, 12])

In [261]:
my_array9 + my_array10

array([111,  25,  25,  26,  25,  27,  30,  28,  29,  33,  33,  33,  33,
        35,  35,  38,  39,  42,  39,  42])

In [265]:
my_matrix9 = my_array9.reshape(4,5)
my_matrix10 = my_array10.reshape(2,10)

In [266]:
my_matrix9

array([[100,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30]])

In [267]:
my_matrix10

array([[11, 13, 12, 12, 10, 11, 13, 10, 10, 13],
       [12, 11, 10, 11, 10, 12, 12, 14, 10, 12]])

In [268]:
# my_matrix9 + my_matrix10

ValueError: operands could not be broadcast together with shapes (4,5) (2,10) 

In [280]:
my_array10[:5]

array([11, 13, 12, 12, 10])

In [271]:
my_matrix9 + my_array10[:5]

array([[111,  25,  25,  26,  25],
       [ 27,  30,  30,  31,  30],
       [ 32,  35,  35,  36,  35],
       [ 37,  40,  40,  41,  40]])

In [272]:
my_matrix9.shape

(4, 5)

In [273]:
my_array10[:5].shape

(5,)

In [274]:
my_array9

array([100,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30])

In [276]:
## testing pakai 3 dimensi
test_matrix = my_array9.reshape(2,2,5)
test_matrix

array([[[100,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20]],

       [[ 21,  22,  23,  24,  25],
        [ 26,  27,  28,  29,  30]]])

In [278]:
test_matrix + my_array10[:5]

array([[[111,  25,  25,  26,  25],
        [ 27,  30,  30,  31,  30]],

       [[ 32,  35,  35,  36,  35],
        [ 37,  40,  40,  41,  40]]])

In [279]:
my_array9 - my_array10

array([89, -1,  1,  2,  5,  5,  4,  8,  9,  7,  9, 11, 13, 13, 15, 14, 15,
       14, 19, 18])

In [281]:
my_array9 / my_array10

array([9.09090909, 0.92307692, 1.08333333, 1.16666667, 1.5       ,
       1.45454545, 1.30769231, 1.8       , 1.9       , 1.53846154,
       1.75      , 2.        , 2.3       , 2.18181818, 2.5       ,
       2.16666667, 2.25      , 2.        , 2.9       , 2.5       ])

In [290]:
my_array9 // my_array10

array([9, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2],
      dtype=int32)

In [282]:
my_array9 * my_array10

array([1100,  156,  156,  168,  150,  176,  221,  180,  190,  260,  252,
        242,  230,  264,  250,  312,  324,  392,  290,  360])

In [304]:
# ** = pangkat
(my_array9**my_array10).astype('uint64')

array([18446744072405123072,           1275068416, 18446744071597093297,
                  344068096,           1124772961,                    0,
                 1196240593,           1349403648, 18446744071562510729,
                 1409286144,            232284689,            885692416,
                 1551643729,                    0,           1977800241,
                 1729826816, 18446744071756170961,            268435456,
       18446744071716339433,            403968000], dtype=uint64)

In [288]:
np.power(my_array9, [3])

array([1000000,    1728,    2197,    2744,    3375,    4096,    4913,
          5832,    6859,    8000,    9261,   10648,   12167,   13824,
         15625,   17576,   19683,   21952,   24389,   27000], dtype=int32)

In [294]:
display(my_array9)
display(np.sqrt(my_array9))

array([100,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30])

array([10.        ,  3.46410162,  3.60555128,  3.74165739,  3.87298335,
        4.        ,  4.12310563,  4.24264069,  4.35889894,  4.47213595,
        4.58257569,  4.69041576,  4.79583152,  4.89897949,  5.        ,
        5.09901951,  5.19615242,  5.29150262,  5.38516481,  5.47722558])

In [296]:
np.log2(8)

3.0

In [297]:
np.log10(100)

2.0

In [300]:
np.log(np.power(2.71828182845904523536028747135266249775724709369995,2))

2.0

In [301]:
np.exp(2)

7.38905609893065

In [302]:
np.mean(my_array9)

24.95

In [306]:
display(my_array9)
np.median(my_array9)

array([100,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30])

21.5

In [324]:
test = np.array([20, 21, 23, 25, 30, 31, 35, 250, 150, 175, 120])
mean_test = test.mean()
mean_test

80.0

In [332]:
test.std(ddof=0)

76.69656860879525

In [328]:
total = 0
for i in test:
    total += (i-mean_test)**2
    
standard_dev = (total/len(test))**.5
standard_dev

76.69656860879525

In [334]:
np.absolute(-2)

2

In [335]:
np.sin(my_array9)

array([-0.50636564, -0.53657292,  0.42016704,  0.99060736,  0.65028784,
       -0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525,
        0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175,
        0.76255845,  0.95637593,  0.27090579, -0.66363388, -0.98803162])

In [336]:
np.cos(my_array9)

array([ 0.86231887,  0.84385396,  0.90744678,  0.13673722, -0.75968791,
       -0.95765948, -0.27516334,  0.66031671,  0.98870462,  0.40808206,
       -0.54772926, -0.99996083, -0.53283302,  0.42417901,  0.99120281,
        0.64691932, -0.29213881, -0.96260587, -0.74805753,  0.15425145])

In [337]:
np.tan(my_array9)

array([-0.58721392, -0.63585993,  0.46302113,  7.24460662, -0.8559934 ,
        0.30063224,  3.49391565, -1.13731371,  0.15158947,  2.23716094,
       -1.52749853,  0.00885166,  1.58815308, -2.1348967 , -0.13352641,
        1.17875355, -3.2737038 , -0.2814296 ,  0.88714284, -6.4053312 ])

## __10. np.append(), np.insert(), np.delete()__

In [338]:
my_array9

array([100,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30])

In [339]:
np.append(my_array9, 31)

array([100,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30,  31])

In [341]:
np.insert(my_array9, 10, 110)

array([100,  12,  13,  14,  15,  16,  17,  18,  19,  20, 110,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30])

In [343]:
np.delete(my_array9, 0)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30])

In [344]:
my_array9

array([100,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30])

## __11. np.vstack() & np.hstack()__

In [345]:
my_array9

array([100,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30])

In [346]:
my_array10

array([11, 13, 12, 12, 10, 11, 13, 10, 10, 13, 12, 11, 10, 11, 10, 12, 12,
       14, 10, 12])

In [348]:
vstack9_10 = np.vstack([my_array9, my_array10])
print(vstack9_10)

[[100  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28
   29  30]
 [ 11  13  12  12  10  11  13  10  10  13  12  11  10  11  10  12  12  14
   10  12]]


In [350]:
vstack9_10.shape

(2, 20)

In [354]:
my_matrix11 = np.random.randint(1,10,[2,20])
my_matrix11

array([[7, 7, 5, 5, 7, 2, 4, 6, 4, 9, 6, 6, 2, 6, 1, 5, 1, 1, 2, 6],
       [8, 3, 4, 7, 1, 3, 5, 1, 9, 3, 5, 9, 8, 7, 1, 2, 7, 7, 7, 5]])

In [355]:
hstack910_11 = np.hstack([vstack9_10, my_matrix11])
hstack910_11

array([[100,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
         24,  25,  26,  27,  28,  29,  30,   7,   7,   5,   5,   7,   2,
          4,   6,   4,   9,   6,   6,   2,   6,   1,   5,   1,   1,   2,
          6],
       [ 11,  13,  12,  12,  10,  11,  13,  10,  10,  13,  12,  11,  10,
         11,  10,  12,  12,  14,  10,  12,   8,   3,   4,   7,   1,   3,
          5,   1,   9,   3,   5,   9,   8,   7,   1,   2,   7,   7,   7,
          5]])

In [356]:
hstack910_11.shape

(2, 40)

In [357]:
my_array12 = my_array10[:10]
my_array12

array([11, 13, 12, 12, 10, 11, 13, 10, 10, 13])

### __11.1 Warning using vstack and hstack__
- Kalau menggunakan vstack perhatikan kolomnya
- Kalau menggunakan hstack perhatikan rownya dan dimensionnya

In [358]:
# error
# np.vstack([my_array9, my_array12])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 20 and the array at index 1 has size 10

In [359]:
np.hstack([my_array9, my_array12])

array([100,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30,  11,  13,  12,  12,  10,  11,
        13,  10,  10,  13])

In [376]:
matrix11_testing = my_matrix11[[0]]
matrix11_testing

array([[7, 7, 5, 5, 7, 2, 4, 6, 4, 9, 6, 6, 2, 6, 1, 5, 1, 1, 2, 6]])

In [379]:
matrix9_testing = my_array9.reshape(2,-1)
matrix9_testing

array([[100,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30]])

In [378]:
my_matrix11

array([[7, 7, 5, 5, 7, 2, 4, 6, 4, 9, 6, 6, 2, 6, 1, 5, 1, 1, 2, 6],
       [8, 3, 4, 7, 1, 3, 5, 1, 9, 3, 5, 9, 8, 7, 1, 2, 7, 7, 7, 5]])

In [380]:
np.hstack([my_matrix11, matrix9_testing])

array([[  7,   7,   5,   5,   7,   2,   4,   6,   4,   9,   6,   6,   2,
          6,   1,   5,   1,   1,   2,   6, 100,  12,  13,  14,  15,  16,
         17,  18,  19,  20],
       [  8,   3,   4,   7,   1,   3,   5,   1,   9,   3,   5,   9,   8,
          7,   1,   2,   7,   7,   7,   5,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30]])

In [362]:
# np.hstack([my_array9, my_matrix11])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [381]:
my_array9

array([100,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30])

In [363]:
np.vstack([my_array9, my_matrix11])

array([[100,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
         24,  25,  26,  27,  28,  29,  30],
       [  7,   7,   5,   5,   7,   2,   4,   6,   4,   9,   6,   6,   2,
          6,   1,   5,   1,   1,   2,   6],
       [  8,   3,   4,   7,   1,   3,   5,   1,   9,   3,   5,   9,   8,
          7,   1,   2,   7,   7,   7,   5]])

## __12. np.concatenate()__

In [382]:
my_array9

array([100,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30])

In [384]:
my_array8

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [387]:
arr8_9_0 = np.concatenate([my_array9, my_array8], axis=0)
arr8_9_0

array([100,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30,  11,  12,  13,  14,  15,  16,
        17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,
        30])

In [409]:
arr8_9_0 = np.concatenate([my_array9.reshape(1,-1), my_array8.reshape(1,-1)], axis=-1)
arr8_9_0

array([[100,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
         24,  25,  26,  27,  28,  29,  30,  11,  12,  13,  14,  15,  16,
         17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,
         30]])

In [399]:
len(my_array9)

20

In [405]:
arr8_9_0 = np.concatenate([my_array9.reshape(2,5,2), my_array8.reshape(2,5,2)], axis=2)
arr8_9_0

array([[[100,  12,  11,  12],
        [ 13,  14,  13,  14],
        [ 15,  16,  15,  16],
        [ 17,  18,  17,  18],
        [ 19,  20,  19,  20]],

       [[ 21,  22,  21,  22],
        [ 23,  24,  23,  24],
        [ 25,  26,  25,  26],
        [ 27,  28,  27,  28],
        [ 29,  30,  29,  30]]])

In [395]:
my_array9.reshape(2,5,-1), my_array8.reshape(2,5,-1)

(array([[[100,  12],
         [ 13,  14],
         [ 15,  16],
         [ 17,  18],
         [ 19,  20]],
 
        [[ 21,  22],
         [ 23,  24],
         [ 25,  26],
         [ 27,  28],
         [ 29,  30]]]),
 array([[[11, 12],
         [13, 14],
         [15, 16],
         [17, 18],
         [19, 20]],
 
        [[21, 22],
         [23, 24],
         [25, 26],
         [27, 28],
         [29, 30]]]))

## __13. np.sort()__

In [410]:
my_array9

array([100,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
        24,  25,  26,  27,  28,  29,  30])

In [411]:
np.sort(my_array9)

array([ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,
        25,  26,  27,  28,  29,  30, 100])

## __14. arr.transpose()__

In [418]:
display(my_matrix9)
display(my_matrix9.shape)

array([[100,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30]])

(4, 5)

In [419]:
my_matrix9_trans = my_matrix9.transpose()
display(my_matrix9_trans)
display(my_matrix9_trans.shape)

array([[100,  16,  21,  26],
       [ 12,  17,  22,  27],
       [ 13,  18,  23,  28],
       [ 14,  19,  24,  29],
       [ 15,  20,  25,  30]])

(5, 4)

In [417]:
my_matrix9.T

array([[100,  16,  21,  26],
       [ 12,  17,  22,  27],
       [ 13,  18,  23,  28],
       [ 14,  19,  24,  29],
       [ 15,  20,  25,  30]])